config/routes.rb
Rails.application.routes.draw do
  resources :zoom_user_actions
  resources :webinar_requests
  devise_for :users
  get 'zoom_users' => 'zoom_users#index'
  get 'pro_users' => 'zoom_users#pro_users'
  get 'basic_users' => 'zoom_users#basic_users'
  get 'webinars' => 'webinars#index'
  get 'recurring_webinars' => 'webinars#recurring_webinars'
  get 'registration_webinars' => 'webinars#registration_webinars'
  post 'create_webinar' => 'webinars#create_webinar'
  post 'toggle_user_type' => 'zoom_users#toggle_user_type'
  post 'demote_user' => 'zoom_user_actions#demote_user'
  post 'promote_user' => 'zoom_user_actions#promote_user'
  get 'zoom_action_logs' => 'zoom_user_actions#logs'
  get 'not_authorized' => 'webinars#not_authorized'

  root to: 'webinars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/zoom_user_action.rb
class ZoomUserAction < ApplicationRecord
end

app/controllers/zoom_users_controller.rb
class ZoomUsersController < ApplicationController
	before_action :set_zoom_api_keys, :get_users
	before_action :authenticate_user!, :authorized, :except => [:not_authorized]

	def get_users
		@zoom_options[:body][:page_size] = 100
    zoom_users = HTTParty.post("https://api.zoom.us/v1/user/list", @zoom_options)
		@zoom_users = zoom_users.parsed_response["users"]
		@pro_users = @zoom_users.select { |user| user['type'] == 2 }
		@basic_users = @zoom_users.select { |user| user['type'] == 1 }
	end

	def toggle_user_type
		@zoom_options[:body][:id] = params[:zoom_user_id]
		user = HTTParty.post("https://api.zoom.us/v1/user/get", @zoom_options)
		if user['type'] == 2
			@zoom_options[:body][:type] = 1
		else
			@zoom_options[:body][:type] = 2
		end
		toggle = HTTParty.post("https://api.zoom.us/v1/user/update", @zoom_options)
		redirect_to zoom_users_path
	end

end

app/helpers/zoom_users_helper.rb
module ZoomUsersHelper
end

app/views/zoom_users/basic_users.html.erb
<p id="notice"><%= notice %></p>

<h1>Zoom Basic Users</h1>
Pro users: <%= @pro_users.count %> 
Basic users: <%= @basic_users.count %> 
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Zoom ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @basic_users.each do |zoom_user| %>
      <tr>
        <td><%= zoom_user['email'] %>(<%= if zoom_user['type'].to_s == '2' then "pro" else "basic" end %> )</td>
        <td><%= zoom_user['id'] %></td>
        <td><%= zoom_user['first_name'] %></td>
        <td><%= zoom_user['last_name'] %></td>
        <td><%= button_to 'Toggle User Type', toggle_user_type_path(zoom_user_id: zoom_user['id']), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/zoom_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zoom Users</h1>
Pro users: <%= @pro_users.count %> 
Basic users: <%= @basic_users.count %> 
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Zoom ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zoom_users.each do |zoom_user| %>
      <tr>
        <td><%= zoom_user['email'] %>(<%= if zoom_user['type'].to_s == '2' then "pro" else "basic" end %> )</td>
        <td><%= zoom_user['id'] %></td>
        <td><%= zoom_user['first_name'] %></td>
        <td><%= zoom_user['last_name'] %></td>
        <td><%= button_to 'Toggle User Type', toggle_user_type_path(zoom_user_id: zoom_user['id']), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/zoom_users/pro_users.html.erb
<p id="notice"><%= notice %></p>

<h1>Zoom Pro Users</h1>
Pro users: <%= @pro_users.count %> 
Basic users: <%= @basic_users.count %> 
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Zoom ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pro_users.each do |zoom_user| %>
      <tr>
        <td><%= zoom_user['email'] %>(<%= if zoom_user['type'].to_s == '2' then "pro" else "basic" end %> )</td>
        <td><%= zoom_user['id'] %></td>
        <td><%= zoom_user['first_name'] %></td>
        <td><%= zoom_user['last_name'] %></td>
        <td><%= button_to 'Toggle User Type', toggle_user_type_path(zoom_user_id: zoom_user['id']), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>