config/routes.rb
Rails.application.routes.draw do
  resources :zoom_user_actions
  resources :webinar_requests
  devise_for :users
  get 'zoom_users' => 'zoom_users#index'
  get 'pro_users' => 'zoom_users#pro_users'
  get 'basic_users' => 'zoom_users#basic_users'
  get 'webinars' => 'webinars#index'
  get 'recurring_webinars' => 'webinars#recurring_webinars'
  get 'registration_webinars' => 'webinars#registration_webinars'
  post 'create_webinar' => 'webinars#create_webinar'
  post 'toggle_user_type' => 'zoom_users#toggle_user_type'
  post 'demote_user' => 'zoom_user_actions#demote_user'
  post 'promote_user' => 'zoom_user_actions#promote_user'
  get 'zoom_action_logs' => 'zoom_user_actions#logs'
  get 'not_authorized' => 'webinars#not_authorized'

  root to: 'webinars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/zoom_user_actions_controller.rb
class ZoomUserActionsController < ApplicationController
  before_action :set_zoom_user_action, only: [:show, :edit, :update, :destroy]
  before_action :set_zoom_api_keys
  before_action :authenticate_user!, :authorized, :except => [:not_authorized, :demote_user, :promote_user]
  skip_before_action :verify_authenticity_token, :only => [:demote_user, :promote_user]

  # GET /zoom_user_actions
  # GET /zoom_user_actions.json
  def index
    @zoom_user_actions = ZoomUserAction.all.order action_date: :desc
  end

  # GET /zoom_user_actions/1
  # GET /zoom_user_actions/1.json
  def show
  end

  # GET /zoom_user_actions/new
  def new
    @zoom_options[:body][:page_size] = 100
    zoom_users = HTTParty.post("https://api.zoom.us/v1/user/list", @zoom_options)
    @zoom_users = zoom_users.parsed_response["users"]
    @pro_users = @zoom_users.select { |user| user['type'] == 2 }
    @basic_users = @zoom_users.select { |user| user['type'] == 1 }
    @zoom_user_action = ZoomUserAction.new
  end

  # GET /zoom_user_actions/1/edit
  def edit
  end

  # POST /zoom_user_actions
  # POST /zoom_user_actions.json
  def create
    @zoom_user_action = ZoomUserAction.new(zoom_user_action_params)
    @zoom_options[:body][:id] = zoom_user_action_params['zoom_user_id']
    user = HTTParty.post("https://api.zoom.us/v1/user/get", @zoom_options)
    @zoom_user_action.zoom_user_name = user['first_name'] + ' ' + user['last_name']
    @zoom_user_action.zoom_user_email = user['email']

    if params[:email_user] == 'true'
      ZoomUserActionsMailer.add_user_action(@zoom_user_action).deliver
    end

    respond_to do |format|
      if @zoom_user_action.save
        format.html { redirect_to @zoom_user_action, notice: 'Zoom user action was successfully created.' }
        format.json { render :show, status: :created, location: @zoom_user_action }
      else
        format.html { render :new }
        format.json { render json: @zoom_user_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zoom_user_actions/1
  # PATCH/PUT /zoom_user_actions/1.json
  def update
    respond_to do |format|
      if @zoom_user_action.update(zoom_user_action_params)
        format.html { redirect_to @zoom_user_action, notice: 'Zoom user action was successfully updated.' }
        format.json { render :show, status: :ok, location: @zoom_user_action }
      else
        format.html { render :edit }
        format.json { render json: @zoom_user_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zoom_user_actions/1
  # DELETE /zoom_user_actions/1.json
  def destroy
    @zoom_user_action.destroy
    respond_to do |format|
      format.html { redirect_to zoom_user_actions_url, notice: 'Zoom user action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def demote_user
    @zoom_options[:body][:id] = params[:zoom_user_id]
    @zoom_options[:body][:type] = 1
    HTTParty.post("https://api.zoom.us/v1/user/update", @zoom_options)
  end

  def promote_user
    @zoom_options[:body][:id] = params[:zoom_user_id]
    @zoom_options[:body][:type] = 2
    if params[:large_meeting] == "true"
      @zoom_options[:body][:enable_large] = true
    end
    @zoom_options[:body][:zoom_user_email] = params[:zoom_user_email]
    
    HTTParty.post("https://api.zoom.us/v1/user/update", @zoom_options)
    #if its a webinar in addtion to making user pro, also set Alternative Host
    if !params[:zoom_webinar_id].empty?
      @zoom_options[:body][:zoom_webinar_id] = params[:zoom_webinar_id] #used by mailer
      @zoom_options[:body][:id] = params[:zoom_webinar_id]
      @zoom_options[:body][:option_alternative_hosts] = params[:zoom_user_email]
      HTTParty.post("https://api.zoom.us/v1/webinar/update", @zoom_options)
    end
    ZoomUserActionsMailer.promote_user_action(@zoom_options).deliver
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zoom_user_action
      @zoom_user_action = ZoomUserAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zoom_user_action_params
      params.require(:zoom_user_action).permit(:zoom_user_id,
                                               :zoom_webinar_id,
                                               :zoom_user_name,
                                               :zoom_user_email,
                                               :action_date,
                                               :large_meeting,
                                               :notes)
    end
end

app/helpers/zoom_user_actions_helper.rb
module ZoomUserActionsHelper
end

app/views/zoom_user_actions/_form.html.erb
<%= form_for(zoom_user_action) do |f| %>
  <% if zoom_user_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zoom_user_action.errors.count, "error") %> prohibited this zoom_user_action from being saved:</h2>

      <ul>
      <% zoom_user_action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zoom_user %>
    <%= select(:zoom_user_action, :zoom_user_id, @basic_users.map {|v| [ v['first_name'] + ' ' + v['last_name'], v['id'] ] }) %>
  </div>

  <div class="field">
    <%= f.label :action_date %>
    <%= f.text_field :action_date, :id => "datepicker" %>
  </div>

  <div class="field">
    <%= f.label "Zoom Webinar ID" %>
    <%= f.text_field :zoom_webinar_id %>
  </div>

  <%= f.check_box :large_meeting %>
  <%= f.label "Large Meeting?" %>

  <%= hidden_field_tag :email_user, false %>
  <%= check_box_tag :email_user, checked = true, {checked: true} %> Email User Immediately? User will still recieve an email on the Action Date specified above.</br></br>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zoom_user_actions/edit.html.erb
<h1>Editing Zoom User Action</h1>

<%= render 'form', zoom_user_action: @zoom_user_action %>

<%= link_to 'Show', @zoom_user_action %> |
<%= link_to 'Back', zoom_user_actions_path %>

app/views/zoom_user_actions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zoom User Actions</h1>&nbsp
Users will be promoted to pro users on the Promotion Date below for 24 hours

<table>
  <thead>
    <tr>
      <th>Zoom user</th>
      <th>Promotion Date</th>
      <th>Webinar ID</th>
      <th>Large meeting</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zoom_user_actions.each do |zoom_user_action| %>
      <tr>
        <td><%= zoom_user_action.zoom_user_name %></td>
        <td><%= zoom_user_action.action_date %></td>
        <td><%= zoom_user_action.zoom_webinar_id %></td>
        <td><%= zoom_user_action.large_meeting %></td>
        <td><%= zoom_user_action.notes %></td>
        <td><%= link_to 'Show', zoom_user_action %></td>
        <td><%= link_to 'Edit', edit_zoom_user_action_path(zoom_user_action) %></td>
        <td><%= link_to 'Destroy', zoom_user_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zoom User Action', new_zoom_user_action_path %>

app/views/zoom_user_actions/logs.html.erb
<pre><%= @logs %></pre>

app/views/zoom_user_actions/new.html.erb
<h1>New Zoom User Action</h1>

<%= render 'form', zoom_user_action: @zoom_user_action %>

<%= link_to 'Back', zoom_user_actions_path %>

app/views/zoom_user_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zoom User Name:</strong>
  <%= @zoom_user_action.zoom_user_name %>
</p>

<p>
  <strong>Zoom User Email:</strong>
  <%= @zoom_user_action.zoom_user_email %>
</p>

<p>
  <strong>Zoom User ID:</strong>
  <%= @zoom_user_action.zoom_user_id %>
</p>

<p>
  <strong>Action date:</strong>
  <%= @zoom_user_action.action_date %>
</p>

<p>
  <strong>Zoom Webinar ID:</strong>
  <%= @zoom_user_action.zoom_webinar_id %>
</p>

<p>
  <strong>Large meeting:</strong>
  <%= @zoom_user_action.large_meeting %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @zoom_user_action.notes %>
</p>

<%= link_to 'Edit', edit_zoom_user_action_path(@zoom_user_action) %> |
<%= link_to 'Back', zoom_user_actions_path %>