config/routes.rb
Rails.application.routes.draw do
  resources :zoom_user_actions
  resources :webinar_requests
  devise_for :users
  get 'zoom_users' => 'zoom_users#index'
  get 'pro_users' => 'zoom_users#pro_users'
  get 'basic_users' => 'zoom_users#basic_users'
  get 'webinars' => 'webinars#index'
  get 'recurring_webinars' => 'webinars#recurring_webinars'
  get 'registration_webinars' => 'webinars#registration_webinars'
  post 'create_webinar' => 'webinars#create_webinar'
  post 'toggle_user_type' => 'zoom_users#toggle_user_type'
  post 'demote_user' => 'zoom_user_actions#demote_user'
  post 'promote_user' => 'zoom_user_actions#promote_user'
  get 'zoom_action_logs' => 'zoom_user_actions#logs'
  get 'not_authorized' => 'webinars#not_authorized'

  root to: 'webinars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/webinar_request.rb
class WebinarRequest < ApplicationRecord
end

app/controllers/webinar_requests_controller.rb
class WebinarRequestsController < ApplicationController
  before_action :set_webinar_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :authorized, :except => [:not_authorized, :create]
  skip_before_action :verify_authenticity_token, :only => [:create]

  # GET /webinar_requests
  # GET /webinar_requests.json
  def index
    @webinar_requests = WebinarRequest.all.order created_at: :desc
  end

  # GET /webinar_requests/1
  # GET /webinar_requests/1.json
  def show
  end

  # GET /webinar_requests/new
  def new
    @webinar_request = WebinarRequest.new
  end

  # GET /webinar_requests/1/edit
  def edit
  end

  # POST /webinar_requests
  # POST /webinar_requests.json
  def create
    @webinar_request = WebinarRequest.new(webinar_request_params)

    respond_to do |format|
      if @webinar_request.save
        format.html { redirect_to @webinar_request, notice: 'Webinar request was successfully created.' }
        format.json { render :show, status: :created, location: @webinar_request }
      else
        format.html { render :new }
        format.json { render json: @webinar_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webinar_requests/1
  # PATCH/PUT /webinar_requests/1.json
  def update
    respond_to do |format|
      if @webinar_request.update(webinar_request_params)
        format.html { redirect_to @webinar_request, notice: 'Webinar request was successfully updated.' }
        format.json { render :show, status: :ok, location: @webinar_request }
      else
        format.html { render :edit }
        format.json { render json: @webinar_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webinar_requests/1
  # DELETE /webinar_requests/1.json
  def destroy
    @webinar_request.destroy
    respond_to do |format|
      format.html { redirect_to webinar_requests_url, notice: 'Webinar request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webinar_request
      @webinar_request = WebinarRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def webinar_request_params
      params.require(:webinar_request).permit(
                      :name,
                      :email,
                      :webinar_date,
                      :webinar_time,
                      :duration,
                      :topic,
                      :agenda,
                      :panelist,
                      :learn_event)

    end
end

app/helpers/webinar_requests_helper.rb
module WebinarRequestsHelper
end

app/views/webinar_requests/_form.html.erb
<%= form_for(webinar_request) do |f| %>
  <% if webinar_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webinar_request.errors.count, "error") %> prohibited this webinar_request from being saved:</h2>

      <ul>
      <% webinar_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :webinar_date %>
    <%= f.text_field :webinar_date %>
  </div>

  <div class="field">
    <%= f.label :webinar_time %>
    <%= f.text_field :webinar_time %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>

  <div class="field">
    <%= f.label :topic %>
    <%= f.text_field :topic %>
  </div>

  <div class="field">
    <%= f.label :agenda %>
    <%= f.text_area :agenda %>
  </div>

  <div class="field">
    <%= f.label :panelist %>
    <%= f.text_field :panelist %>
  </div>

  <div class="field">
    <%= f.label :learn_event %>
    <%= f.text_field :learn_event %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/webinar_requests/edit.html.erb
<h1>Editing Webinar Request</h1>

<%= render 'form', webinar_request: @webinar_request %>

<%= link_to 'Show', @webinar_request %> |
<%= link_to 'Back', webinar_requests_path %>

app/views/webinar_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webinar Requests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Webinar date</th>
      <th>Webinar time</th>
      <th>Duration</th>
      <th>Topic</th>
      <th>Agenda</th>
      <th>Panelist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webinar_requests.each do |webinar_request| %>
      <tr>
        <td><%= webinar_request.name %></td>
        <td><%= webinar_request.email %></td>
        <td><%= webinar_request.webinar_date %></td>
        <td><%= webinar_request.webinar_time %></td>
        <td><%= webinar_request.duration %></td>
        <td><%= webinar_request.topic %></td>
        <td><button class="button" type="button" data-toggle="dropdown-pane-<%= webinar_request.id %>">View</button>
        <div class="dropdown-pane" id="dropdown-pane-<%= webinar_request.id %>" data-dropdown>
            <%= webinar_request.agenda %><br/></div></td>
        <td><%= webinar_request.panelist %></td>
        <td><%= link_to 'Show', webinar_request %></td>
        <td><%= link_to 'Edit', edit_webinar_request_path(webinar_request) %></td>
        <td><%= link_to 'Destroy', webinar_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= button_to 'Create Webinar', {controller: "webinars", :action => "create_webinar",
                                                              topic: webinar_request.topic,
                                                              start_date: webinar_request.webinar_date,
                                                              start_time: webinar_request.webinar_time},
                                                              method: :post %></td>
                                                     
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webinar Request', new_webinar_request_path %>

app/views/webinar_requests/new.html.erb
<h1>New Webinar Request</h1>

<%= render 'form', webinar_request: @webinar_request %>

<%= link_to 'Back', webinar_requests_path %>

app/views/webinar_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @webinar_request.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @webinar_request.email %>
</p>

<p>
  <strong>Webinar date:</strong>
  <%= @webinar_request.webinar_date %>
</p>

<p>
  <strong>Webinar time:</strong>
  <%= @webinar_request.webinar_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @webinar_request.duration %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @webinar_request.topic %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @webinar_request.agenda %>
</p>

<p>
  <strong>Panelist:</strong>
  <%= @webinar_request.panelist %>
</p>

<%= link_to 'Edit', edit_webinar_request_path(@webinar_request) %> |
<%= link_to 'Back', webinar_requests_path %>